version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--config", "/etc/mongod.conf"]

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/google_docs
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5137:5137"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongo-data:
